### ISSUE TITLE
Some question about the redux-persist-state-manager

### ISSUE THREAD

**Issue by wellyshen** [rt2zz/redux-persist-state-manager#1]
@rt2zz 

Thank you for this repo, I have some questions about it :
1. What's the purpose of the `stateMigrations`, is kind of "blacklist / whitelist"? Should I use it in general case?
2. What's the purpose of the `version`? Should it be including for the configuration?
3. Can the original configure of the `persistStore` of the redux-persist work with the redux-persist-state-manager?

**Comment by rt2zz** [comment]
thanks, yes we should make all of these things more clear in the docs
1. stateMigrations are the code that will run to update stored state to the current running version of state. So if e.g. a user stores state with version 1, then later they load the app and it is on state version 5, migrations 2, 3, 4, and 5 will be run on the rehydrate payload before merging into redux state.
2. version is an integer which determines which migrations to run during rehydrate. Since any given user may have stored any given version, the version is used to determine which migrations to run.
3. `stateManager` is a replacement for `autoRehydrate`. Essentially it does the same thing plus migrations, and a few functionality tweaks.

Let me know if that makes sense. I will try to improve the docs this week, help appreciated!

**Comment by wellyshen** [comment]
@rt2zz Thank you for your response, I am really confused by the relationship of the `stateMigrations` and `version`, if there's a simple use case or scenario in the doc, which will be great :)

**Comment by rt2zz** [comment]
perhaps this explanation will help: https://github.com/rt2zz/redux-persist-state-manager/blob/master/README.md#how-migrations-work

**Comment by wellyshen** [comment]
@rt2zz Thank you very much, now I understand how the `version` of the `stateManager` works. Can you give me a briefly example of what scenario that user need to do the migrating?

**Comment by rt2zz** [comment]
The most common case is the a new release of your app has breaking state changes. Maybe you changed the shape of your models. In this case it is often simplest to simply reset stored state hence you migration might look like 
```
{
    '1': (state) => ({}) 
}
```
Then later perhaps you rename a reducer from `user` to `auth`, now you add a new migration:
```js
{
    '1': (state) => ({}),
    '2': (state) => {
        const auth = state.user
        delete state.user
        return {...state, auth}
    }
}
```

**Comment by wellyshen** [comment]
@rt2zz 

1. At beginning (if there's nothing need to be migrated), what should I set for the `stateManager`?

2. If the following settings need to be used for reseting my store?
```javascript
{
    '1': (state) => ({}), // Should I need it for reseting before a breaking change?
    '2': (state) => {
        // something new...
    }
}
```

**Comment by rt2zz** [comment]
1.  yes only add migration `1` if you have a breaking change and want to reset the client
2. for resetting the store you only need `1`. migration `2` would be if you need to do more updates later.

In the beginning simply set version = 1 and no migration required.

**Comment by wellyshen** [comment]
@rt2zz So, the following code will be my initial setting (no migration required), right?

```javascript
import stateManager from 'redux-persist-state-manager'

import rootReducer from './reducers'

const VERSION = 1
const stateManagedReducer = stateManager(rootReducer, { version: VERSION });
```

**Comment by rt2zz** [comment]
well migrations is a required argument so pretty close:
```js
import stateManager from 'redux-persist-state-manager'

import rootReducer from './reducers'

const VERSION = 1
const stateManagedReducer = stateManager(rootReducer, { version: VERSION }, {});
```

**Comment by wellyshen** [comment]
@rt2zz Thank you a lot :)

**Comment by wellyshen** [comment]
@rt2zz If you can release an example, it will help many people to understand it more easily :)
